<?php


class classTexto {
    

    public function textoJornadaReal(){
        $fonteGaramond = "font-family: garamond; text-align: justify";
        $fonteTamanho = "font-size: 20px"; // Antes da garamond, 14px
        
        //Primeira parte =======================================================================
        
        echo "<div class='row' style='color: #1f226d;'>";
        echo "<div style='height: 20px;'></div>";
        echo "<div class='col-xs-6 col-sm-5'>";
        echo "<ul class='list-inline' style='".$fonteTamanho."; ".$fonteGaramond.";'>";
        echo "  <li>1. A Jornada Real é, por excelência, um caminho espiritual, afinado com o conceito de sadhana da tradição védica, que esclarece que todas as atividades do viver comum podem ser assumidas como oportunidades para o desenvolvimento espiritual  e, por fim, para a própria iluminação.</li>";
        echo "  <li>&nbsp;</li>";
        echo "  <li>2. O programa da Jornada Real (JR), voltado para autoconhecimento, valoriza um investimento diário por parte do interessado, com um encontro semanal em que o focalizador informa as atividades de tal programa.</li>";
        echo "  <li>&nbsp;</li>";
        echo "  <li>3. Seus dois ciclos principais são o diário e o semanal. O diário implica na valorização da prática individual e o semanal, no encontro grupal dos afins para a troca de experiência.</li>";
        echo "  <li>&nbsp;</li>";
        echo "  <li>4. Concebemos a Jornada diária, com dois portais de mudança de consciência como momentos propícios para atividades específicas de autoconhecimento e autotransformação. O portal da noite (PN), onde se realiza a retrospectiva do dia, e o portal da manhã (PM), onde se registra os sonhos. Há recursos próprios para incentivar exercícios de autoterapia com estes conteúdos.</li>";
        echo "</ul>";
        echo "</div>";
        echo "<div class='col-xs-6 col-sm-7' align='center'>";
        echo "  <img src='images/logoJrColor.png' width='300' height='250' class='img-responsive'>";
        echo "</div>";
        echo "</div>"; // Fecha o div class row
        
        //Segunda parte =======================================================================
        
        echo "<div class='row' style='color: #1f226d;'>";
        echo "<div style='height: 20px;'></div>";
        echo "<div class='col-xs-6 col-sm-6' align='center'>";
        echo "  <img src='images/jrLogoColorAzul.png' width='300' height='250' class='img-responsive'>";
        echo "</div>";
        echo "<div class='col-xs-6 col-sm-6'>";
        echo "<ul class='list-inline' style='".$fonteTamanho."; ".$fonteGaramond.";'>";
        echo "      <li>5. A meditação é prática fundamental em todo o percurso, realizada diariamente, e técnicas específicas são ensinadas.<br>";
        echo "      <br>6. Mensalmente, há atividades de auto-avaliação.";
        echo "      <li>&nbsp;</li>";
        echo "      <li>7. Este programa é passado através de um Livro de Programa, sendo cada estação contemplada com um volume.</li>";
        echo "      <li>&nbsp;</li>";
        echo "      <li>8. O mestre desta jornada é a própria pessoa, e para ela assumir esta função tem como recurso auxiliar os registros diários por escrito, no Livro de Programa, assim como no seu Caderno de Diário.</li>";
        echo "      <li>&nbsp;</li>";
        echo "      <li>9. Estes registros quando consultados, isoladamente ou em série, constituem retorno valioso para as suas periódicas avaliações. Sem estas anotações dificilmente a jornada é realizada a contento.</li>";
        echo "      <li>&nbsp;</li>";
        echo "      <li>10. Além deste Livro, é distribuída uma Tabuleta da Prática, que serve para o registro de algumas das suas atividades e tarefas.</li>";
        echo "      <li>&nbsp;</li>";
        echo "      <li>11. O programa funciona como uma atividade de autoterapia, o que não dispensa uma terapia individual, como recurso afinado, caso a pessoa tenha interesse em fazer ou já a realize.</li>";
        echo "</ul>";
        echo "</div>";
        echo "</div>";

        //Terceira parte
        
        echo "<div class='row' style='color: #1f226d;'>";
        echo "  <div style='height: 20px;'></div>";
        echo "      <div class='col-xs-6 col-sm-6'>";
        echo "          <ul class='list-inline' style='".$fonteTamanho."; ".$fonteGaramond.";'>";
        echo "              <li>";
        echo "                  12. O programa e a sua produção estará presente neste conjunto:";
        echo "                  <br><br>";
        echo "                      a) Livro de Programa – oferecido em 4 volumes, um para cada estação;";
        echo "                  <br>";
        echo "                      b) Tabuleta da Prática – oferecida.";
        echo "                  <br>";
        echo "                      c) Caderno de Diário – próprio.";
        echo "                  <br>";
        echo "                  <br>";
        echo "                  13. A conclusão do ano-Jornada Real ocorre por meio de uma semana de retiro, visando a intensificação da prática deste programa. Sua adesão, apesar de não obrigatória, é fortemente recomendada.";
        echo "              </li>";
        echo "              <li>";
        echo "                  <span  style='padding-left: 20px;'>Como a JR tem a duração de um ano, seguindo as estações, seu curso termina em setembro quando se finaliza o inverno (coincidindo com o feriado de 7 de setembro), com o Retiro anual. Seu objetivo é intensificar a prática deste programa, num lugar apropriado para este tipo de recolhimento – o Espaço de Convivência Morgenlicht (<abbr title='http://www.morgenlicht.com.br'><a href='http://www.morgenlicht.com.br' target='_blank'>http://www.morgenlicht.com.br</a></abbr>). O Morgenlicht, com sua beleza e conforto, oferece um entorno favorável à introspecção e à harmonização dos nossos corpos e mente. A alimentação, cuidada com esmero, associa prazer com leveza, saúde com bem-estar.</span>";
        echo "              </li>";
        echo "          </ul>";
        echo "      </div>";
        echo "  <div class='col-xs-6 col-sm-6' align='center'>";
        echo "  <img src='images/jrLogoColorRoxo.png' width='300' height='250' class='img-responsive'>";
        echo "  </div>";
        echo "</div>";//Fecha a div row

        //Quarta parte
        
        echo "<div class='row' style='color: #1f226d;'>";
        echo "  <div style='height: 20px;'></div>";
        echo "      <div class='col-xs-6 col-sm-6' align='center'>";
        echo "          <img src='images/jrLogoColorVerde.png' width='300' height='250' class='img-responsive'>";
        echo "      </div>";
        echo "      <div class='col-xs-6 col-sm-6'>";
        echo "          <ul class='list-inline' style='".$fonteTamanho."; ".$fonteGaramond.";'>";
        echo "              <li>14. Atualmente, oferecemos 3 grupos de encontros semanais, com duração de 2 horas:<br><br>";
        echo "                  1) 3a feira - 18h;<br>";
        echo "                  2) 4a feira - 14h30;<br>";
        echo "                  3) 5a feira - 18h30.";
//        echo "              </li>";
//        echo "              <li>&nbsp;</li>";
        echo "              <br><br>";
        echo "              15. Há um encontro mensal, aos domingos, de 9 às 13h, em que se concentra a transmissão do programa do mês. Caso haja vagas, quem frequenta o grupo semanal, poderá também participar do grupo mensal, sem custo adicional.</li>";
        echo "              <li>&nbsp;</li>";
        echo "              <li>16. O investimento financeiro é R$ 50,00 (cinquenta reais) por encontro, pagos mensalmente, no início do período. Em cada estação há 2 meses de 4 semanas, cujo valor é de R$ 200,00 (duzentos reais), e 1 mês de 5 semanas, cujo valor de investimento é de R$ 250,00 (duzentos e cinquenta reais). Este valor é o mesmo para o grupo semanal e para o grupo mensal.</li>";
        echo "              <li>&nbsp;</li>";
        echo "              <li>17. A Jornada Real é parte de um projeto maior – a RedeUnaViva, uma rede espiritual a serviço de uma cultura de paz, organizada sem fins lucrativos. Suas atividades são focalizadas por colaboradores que se dedicam em regime de doação voluntária. A RUV será melhor detalhada em momento oportuno.</li>";
        echo "          </ul>";
        echo "      </div>";
        echo "</div>"; // Fecha o div class row
        
        //Quinta parte
        
        echo "<div class='row' style='color: #1f226d;'>";
        echo "  <div style='height: 20px;'></div>";
        echo "      <div class='col-xs-6 col-sm-6'>";
        echo "          <ul class='list-inline' style='".$fonteTamanho."; ".$fonteGaramond.";'>";
        echo "              <li>";
        echo "                  18. A inscrição é feita mediante preenchimento do Formulário de Adesão, que pode ser conseguido por e-mail. Não há um compromisso de permanência depois de ter sido feita a inscrição. Isto é, caso não esteja satisfeita ou por outros motivos, a pessoa pode desfazer, em qualquer momento, o compromisso de permanecer na Jornada.";
        echo "              <br><br>";
        echo "                  19. A conclusão do ano-Jornada Real ocorre por meio de uma semana de retiro, visando a intensificação da prática deste programa. Sua adesão, apesar de não obrigatória, é fortemente recomendada.";
        echo "              </li>";
        echo "          </ul>";
        echo "      </div>";
        echo "  <div class='col-xs-6 col-sm-6' align='center'>";
        echo "  <img src='images/jrLogomarca.png' width='300' height='250' class='img-responsive'>";
        echo "  </div>";
        echo "</div>";//Fecha a div row
        
        //Sexta parte
        
        echo "<div class='row' style='color: #1f226d;'>";
        echo "  <div style='height: 20px;'></div>";
        echo "      <div class='col-xs-6 col-sm-6' align='center'>";
        echo "          <img src='images/jrLogoColorRoxoClaro.png' width='300' height='250' class='img-responsive'>";
        echo "      </div>";
        echo "  <div class='col-xs-6 col-sm-6'>";
        echo "      <ul class='list-inline' style='".$fonteTamanho."; ".$fonteGaramond.";'>";
        echo "              <li>";
        echo "                  20. A sua entrada somente poderá ser feita até dois meses de iniciado. Seu início, em 2015, se dará na semana, cujo domingo é dia 20 de setembro, considerado o primeiro dia da semana.";
        echo "              <br><br>";
        echo "                  21. Para se inscrever use o <a href='formAdesao.php' href='_self' style='color: #3F6CA1'>Formulário de Adesão (JR)</a>.";
        echo "              </li>";
        echo "          </ul>";
        echo "  </div>";
        echo "</div>";//Fecha a div row
    }
    
    public function textoQuemSomos(){
        $tamanhoFonte16="font-size: 20px; font-family: garamond; text-align: justify;";
        
        echo "<p style='height: 15px;'>&nbsp;</p>";
        echo "<div class='col-md-1'></div>";
        echo "<div class='col-md-4' style='".$tamanhoFonte16."'>";
        echo "  <div class='row'>";
        echo "      <ul class='list-inline' style='text-align: left;'>";
        echo "          <li>";
        echo "              Somos nove pessoas que,<br/>";
        echo "              com um <i>programa diário de autoconhecimento</i><br/>";
        echo "              cuja prática principal é a meditação,<br/>";
        echo "              visamos a transformação própria e do mundo<br/>";
        echo "              tendo como campo de trabalho<br/>";
        echo "              as desafiadoras relações interpessoais.<br/>";
        echo "          </li>";
        echo "      </ul>";
        echo "  </div>";
        echo "</div>";
        echo "<div class='col-md-2' style='".$tamanhoFonte16."'>";
        echo "  <div class='row'>";
        echo "      &nbsp;";
        echo "  </div>";
        echo "</div>";
        echo "<div class='col-md-4' style='".$tamanhoFonte16."'>";
        echo "  <div class='row'>";
        echo "      <ul class='list-inline' style='text-align: left;'>";
        echo "          <li>";
        echo "              Pela riqueza da experiência compartilhada,<br/>";
        echo "              em reuniões semanais<br/>";
        echo "              que deram consistência à proposta,<br/>";
        echo "              decidimos,<br/>";
        echo "              após sete anos de trabalho,<br/>";
        echo "              divulgar esta <b><i>Jornada Real</i></b><br/>";
        echo "          </li>";
        echo "      </ul>";
        echo "  </div>";
        echo "</div>";
        echo "<div class='col-md-1'></div>";
        echo "<div class='col-md-12'>&nbsp;</div>";

        echo "<div class='col-md-12'>";
        echo "  <div class='text-center' style='".$tamanhoFonte16."; text-align: center;'>";
        echo "      convidando pessoas afins <br/>";
        echo "      a tornarem-se companheiros na <b>RedeUnaViva.</b>";
        echo "  </div>";
        echo "</div>";

        echo "<div class='col-md-12'>&nbsp;</div>";
        echo "<div class='col-md-12'>&nbsp;</div>";
        echo "<div class='col-md-12'>";
        echo "<div class='table-responsive'>";
        echo "  <table class='table table-bordered text-center' style='".$tamanhoFonte16."'>";//table-hover 
        echo "      <tr id='corTabela'>";
        echo "          <td>";
        echo "              <abbr title='didamour@globo.com' style='font-size: 20px; color: #3F6CA1;'><b>Diana D'Amour Alexander</b></abbr>";
        echo "                  <br/><br/>";
        echo "                  <b>Médica</b><br/><br/>";
        echo "                  Focalizadora da Jornada Real<br/>";
        echo "                  Participante da RedeUnaViva";
        echo "          </td>";
        echo "          <td>";
        echo "              <abbr title='depaiva.marcia9@gmail.com' style='font-size: 20px; color: #3F6CA1;'><b>Marcia de Paiva</b></abbr>";
        echo "                  <br/><br/>";
        echo "                  <b>Médica e Docente</b><br/><br/>";
        echo "                  Focalizadora da Jornada Real<br/>";
        echo "                  Participante da RedeUnaViva";
        echo "          </td>";
        echo "          <td>";
        echo "              <abbr title='karis.maria@globo.com' style='font-size: 20px; color: #3F6CA1;'><b>Káris Rodrigues</b></abbr>";
        echo "                  <br/><br/>";
        echo "                  <b>Médica e Professora Universitária</b><br/><br/>";
        echo "                  Focalizadora da Jornada Real<br/>";
        echo "                  Participante da RedeUnaViva";
        echo "          </td>";
        echo "      </tr>";
        echo "      <tr id='corTabela'>";
        echo "          <td>";
        echo "              <abbr title='ligialind@ig.com.br' style='font-size: 20px; color: #3F6CA1;'><b>Ligia Lindbergh</b></abbr>";
        echo "                  <br/><br/>";
        echo "                  <b>Psicoterapeuta Transpessoal</b><br/><br/>";
        echo "                  Focalizadora da Jornada Real<br/>";
        echo "                  Participante da RedeUnaViva";
        echo "          </td>";
        echo "          <td>";
        echo "              <abbr title='luiz.bernal@gmail.com' style='font-size: 20px; color: #3F6CA1;'><b>Luiz Carlos Bernal</b></abbr>";
        echo "                  <br/><br/>";
        echo "                  <b>Médico e Psicoterapeuta</b><br/><br/>";
        echo "                  Idealizador da Jornada Real<br/>";
        echo "                  e da RedeUnaViva";
        echo "          </td>";
        echo "          <td>";
        echo "              <abbr title='carlamfontes@yahoo.com.br' style='font-size: 20px; color: #3F6CA1;'><b>Carla Fontes</b></abbr>";
        echo "                  <br/><br/>";
        echo "                  <b>Psicóloga Clínica</b><br/><br/>";
        echo "                  Focalizadora da Jornada Real<br/>";
        echo "                  Participante da RedeUnaViva";
        echo "          </td>";
        echo "      </tr>";
        echo "      <tr id='corTabela'>";
        echo "          <td>";
        echo "              <abbr title='marialuciapereira2@gmail.com' style='font-size: 20px; color: #3F6CA1;'><b>Maria Lucia Pereira</b></abbr>";
        echo "                  <br/><br/>";
        echo "                  <b>Psicóloga</b><br/><br/>";
        echo "                  Focalizadora da Jornada Real<br/>";
        echo "                  Leitora voluntária de história para criança<br/>";
        echo "                  (Instituto Fernandes Figueira)<br/>";
        echo "                  Participante da RedeUnaViva";
        echo "          </td>";
        echo "          <td>";
        echo "              <abbr title='humbertogabarito@gmail.com' style='font-size: 20px; color: #3F6CA1;'><b>Humberto Alves</b></abbr>";
        echo "                  <br/><br/>";
        echo "                  <b>Empresário</b><br/>";
//        echo "                  Idealizador da Jornada Real<br/>";
        echo "                    <br/>";
        echo "                    Participante da RedeUnaViva";
        echo "          </td>";
        echo "          <td>";
        echo "              <abbr title='fernandacappelli@hotmail.com' style='font-size: 20px; color: #3F6CA1;'><b>Fernanda Seixas</b></abbr>";
        echo "                  <br/><br/>";
        echo "                  <b>Cantora</b><br/><br/>";
        echo "                  Participante da RedeUnaViva<br/>";
        echo "          </td>";
        echo "      </tr>";
        echo "  </table>";
//        echo "<div class='text-center'>";
//        echo "  (A minha apresentação é apenas ";
//        echo "</div>";
        echo "</div>";
        echo "</div>";
    }
    
    public function textoYoga(){
        $tamanhoFonte16 = "font-size: 20px; font-family: garamond; text-align: justify;";
        echo "<div class='col-md-1'>";
        echo "  &nbsp;";
        echo "</div>";
        echo "<div class='col-md-10' style='".$tamanhoFonte16."'>";
        echo "  <p>";
        echo "      Segundo <b>Patanjali</b> nos yogasutras, <abbr title='yoga citta vrtti nirodah'><i>yoga citta vrtti nirodah</i></abbr> traduz-se por \"<b>yoga é pacificação das atividades da mente</b>\".<br/>";
        echo "  </p>";
        echo "  <p>";
        echo "      Nesse estado, o praticante desfruta de sua própria natureza e não é mais afetado pelas oscilações da mente.";
        echo "  </p>";
        echo "  <p>";
        echo "      Para se atingir esse estado, não há fórmula fixa, o praticante deve encontrar a prática adequada a ele.<br/>";
        echo "  </p>";
        echo "  <p>";
        echo "      Quando falamos de prática, existem inúmeras tais como a física (<i>asanas</i>), as respiratórias (<i>pranayama</i>), canto de mantras, entre outras.<br/><br/>";
        echo "  </p>";
        
        //Eduardo Quintela
        echo "  <p style='text-align: justify;'>";
        echo "      <abbr title='Eduardo Quintella' style='font-size: 20px; color: #3F6CA1;'><b>Eduardo Quintella</b></abbr> (<a href='mailto:duda.quintella@gmail.com' class='text-link'>duda.quintella@gmail.com</a>)<br/>";
        echo "  <p style='text-align: justify;'>";
        echo "      Pratico yoga desde os 18 anos. Para aprofundar esta investigação além do contato frequente com meus professores, já estive na Índia por duas vezes, para estágios prolongados.<br/>";
        echo "  </p>";
        echo "  <p style='text-align: justify;'>";
        echo "      Como professor, procuro adequar a prática à individualidade de cada aluno para que a desfrute de acordo com as suas possibilidades.";
        echo "  </p>";
//        echo "<div class='imageRow'>";
//        echo "  <div class='set'>";
//        echo "      <div class='single first'>";
//        echo "          <a href='images/yoga/foto1.jpg' rel='lightbox[plants]' title='Foto 1'>";
//        echo "              <img src='images/yoga/foto1.jpg' alt='Foto 1 de 12' style='height: 90px; width: 135px;'/>";
//        echo "          </a>";
//        echo "          <a href='images/yoga/foto2.jpg' rel='lightbox[plants]' title='Foto 2'>";
//        echo "              <img src='images/yoga/foto2.jpg' alt='Foto 2 de 12' style='height: 90px; width: 135px;'/>";
//        echo "          </a>";
//        echo "      </div>";
//        echo "  </div>";
//        echo "</div>";
        
        //Heiko Hoschke
        echo "<p style='height: 20px;'>&nbsp;</p>";
        echo "  <p style='text-align: justify;'>";
        echo "      <abbr title='Heiko Hoschke' style='font-size: 20px; color: #3F6CA1;'><b>Heiko Hoschke</b></abbr> (<a href='mailto:heikosunwu@yahoo.com.br' class='text-link'>heikosunwu@yahoo.com.br</a>)<br/>";
        echo "  <p style='text-align: justify;'>";
        echo "      Método de yoga baseado no sistema Iyengar com o professor Heiko Roschke<br/>";
        echo "  </p>";
        echo "  <p style='text-align: justify;'>";
        echo "      Agreguei meus conhecimentos como fisioterapeuta e como professor de artes marciais ao método de yoga baseado no sistema Iyengar. Este método prioriza o alongamento e o alinhamento propiciando ao praticante forte consciência corporal, tornando perceptíveis os seus vícios posturais e possibilitando a sua correção.";
        echo "  </p>";
        echo "</div>";
        echo "<div class='col-md-1'>";
        echo "  &nbsp;";
        echo "</div>";
    }
    
    public function textoMeditacaoCrista(){
        $tamanhoFonte16 = "font-size: 20px";
        $margem = "margin-left: 0px; text-align: justify";
        echo "<div class='row' style='color: #1f226d;'>";
        echo "  <div style='height: 50px;'></div>";
        echo "      <div class='col-xs-6 col-sm-6'>";
        echo "          <ul class='list-inline' style='font-size: 20px; text-align: justify; font-family: garamond;'>";
        echo "              <li>";
        echo "                  <span style='".$margem.";'>";
        echo "                      Em todos os domingos nos encontramos na nossa sede para realizar nossa costumeira e nutridora <b>Meditação Cristã (MC)</b>.";
        echo "                  </span>";
        echo "              <br><br>";
        echo "                  <span style='".$margem.";'>";
        echo "                      No decorrer da semana dispomos aqui o texto do Evangelho com sua indagação reflexiva, como preparação para a ceia do espírito.";
        echo "                  </span>";
        echo "              <br><br>";
        echo "                  <span style='".$margem.";'>";
        echo "                      São todos convidados e bem vindos.";
        echo "                  </span>";
        echo "              <br><br>";
        echo "                  <p style='color: #31708f; ".$margem.";'><b>DOMINGO - 17 às 19h</b>.</p><br/>";
//        echo "                  <a href='downloads/meditacaocrista/MeditacaoCristaConviteMC59.pdf' target='_blank'>Clique aqui</a> para ler o texto do Evangelho para a MC da semana.";
//        echo "              <br><br>";
        echo "                  <a href='contato.php#mapa' target='_self' style='".$margem.";'>Clique aqui</a> para visualização do mapa, indicando como chegar no endereço.";
        echo "              </li>";
        echo "              <li style='font-size: 20px;'>";
        echo "              <br><br>";
        echo "                  <b>Texto do Evangelho desta semana - 01/11/15</b><br>";
        echo "                  <b>MC 59</b><br>";
        echo "              <br><br>";
        echo "                  <a role='button' data-toggle='collapse' href='#leitura1' aria=expanded='false' aria-controls='collapseLeitura1' style='".$margem.";'>Clique aqui</a> para ler nesta página.";// data-toggle='modal' COLLAPSE
        echo "              <br><br>";
        echo "                  <a role='button' data-toggle='collapse' href='#downloads' aria=expanded='false' aria-controls='collapseDownloads' style='".$margem.";'>Clique aqui</a> para efetuar o download do arquivo ou ler o texto do Evangelho para a MC da semana.";
        echo "              <br><br>";
        echo "              </li>";
        echo "          </ul>";
        echo "      </div>";

        echo "      <div class='col-xs-6 col-sm-6' align='center'>";
        echo "          <div style='height: 5px;'>&nbsp;</div>";
        echo "          <img src='images/meditacaoCrista.jpg' width='550' height='500' class='img-responsive'>";
//        echo "      </div>";
        echo "  <div style='height: 10px; font-family: garamond; font-size: 20px;'>&nbsp;</div>";
        echo "      <a role='button' data-toggle='collapse' href='#downloads' aria=expanded='false' aria-controls='collapseDownloads'>Download das Composições da MC</a><br>";
        echo "      (Textos da MC do número 1 ao 59)";
        echo "  </div>";
        echo "</div>";//Fecha a div row
        
        echo "<div class='collapse' id='downloads'>";
        echo "<div class='row' style='font-family: garamond; font-size: 20px; color: #1f226d;'>";
        echo "  <div class='col-xs-2 col-sm-2 col-md-2'>&nbsp;</div>";
        echo "  <div class='col-xs-8 col-sm-8 col-md-8'>";
        echo "  <div class='text-center'>";
        echo "      <div class='table-responsive'>";
        echo "          <table class='table small'>";
        echo "              <tr style='background-color: #87CEFA;'>";
        echo "                  <td colspan='6'>";
        echo "                      <b>MEDITAÇÃO CRISTÃ - COMPOSIÇÃO</b>";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr class='warning'>";
        echo "                  <td colspan='6'>";
        echo "                      Quando já tiver seu programa, verifique a data de atualização para saber se está atualizado";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr>";
        echo "                  <td style='background-color: #FFFF00;'>";
        echo "                      Parte 1";
        echo "                  </td>";
        echo "                  <td style='background-color: #DB7093;'>";
        echo "                      Parte 2";
        echo "                  </td>";
        echo "                  <td style='background-color: #93DB70;'>";
        echo "                      Parte 3";
        echo "                  </td>";
        echo "                  <td style='background-color: #6495ED;'>";
        echo "                      Parte 4";
        echo "                  </td>";
        echo "                  <td style='background-color: #FFE4E1;'>";
        echo "                      Parte 5";
        echo "                  </td>";
        echo "                  <td style='background-color: #FFA500;'>";
        echo "                      Parte 6";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr class='warning'>";
        echo "                  <td>";
        echo "                      Atualizado em 10/11/2015";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      Atualizado em 10/11/2015";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      Atualizado em 10/11/2015";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      Atualizado em 10/11/2015";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      Atualizado em 10/11/2015";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      Atualizado em 10/11/2015";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr>";
        echo "                  <td>";
        echo "                      1";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      15";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      19";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      32";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      40";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      50";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr class='warning'>";
        echo "                  <td>";
        echo "                      2";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      16";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      20";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      33";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      41";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      51";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr>";
        echo "                  <td>";
        echo "                      3";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      17";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      21";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      34";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      42";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      52";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr class='warning'>";
        echo "                  <td>";
        echo "                      4";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      18";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      22";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      35";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      43";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      53";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr>";
        echo "                  <td>";
        echo "                      5";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      23";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      36";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      44";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      54";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr class='warning'>";
        echo "                  <td>";
        echo "                      6";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      24";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      37";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      45";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      55";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr>";
        echo "                  <td>";
        echo "                      7";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      25";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      38";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      46";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      56";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr class='warning'>";
        echo "                  <td>";
        echo "                      8";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      26";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      39";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      47";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      57";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr>";
        echo "                  <td>";
        echo "                      9";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      27";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      48";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      58";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr class='warning'>";
        echo "                  <td>";
        echo "                      10";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      28";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      49";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      59";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr>";
        echo "                  <td>";
        echo "                      11";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      29";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      60";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr class='warning'>";
        echo "                  <td>";
        echo "                      12";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      30";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr>";
        echo "                  <td>";
        echo "                      13";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      31";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr class='warning'>";
        echo "                  <td>";
        echo "                      14";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      32";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "                  <td>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "              </tr>";
        echo "              <tr style='background-color: #87CEFA;'>";
        echo "                  <td colspan='6'>";
        echo "                      &nbsp;";
        echo "                  </td>";
        echo "              </tr>";
        echo "          </table>";
        echo "      </div>";
        echo "      </div>";
        echo "  </div>";
        echo "  <div class='col-xs-2 col-sm-2 col-md-2'>&nbsp;</div>";
        echo "</div>";
        echo "</div>";
        
        echo "<p style='height: 30px;'>&nbsp;</p>";
        
        
        //Collapse
        echo "<div class='collapse' id='leitura1'>";
        echo "  <div class='well'>";
            echo "<div class='row' style='font-family: garamond; font-size: 20px; color: #1f226d;'>";
            echo "  <div class='col-xs-12 col-md-12'>";
            echo "      <div class='text-center'>";
            echo "          59. <label style='color: blue;'>RedeUnaViva: Meditação Cristã <label style='color: red;'>59</label> – paragem <label style='color: red;'>123</label> – <label style='color: red;'>01.11.2015</label></label>";
            echo "      </div>";
            echo "      <div align='right' style='padding-right: 50px;'><small>MATEUS 6:1-4</small></div>";
            echo "      <div class='text-center'>";
            echo "          SERMÃO DO MONTE – X – Quanto à Esmola: Não Saiba sua Mão Esquerda o que a Direita Faz<br/>ou<br/>O Tesouro Secreto";
            echo "      </div>";
            echo "      <div class='table-responsive'>";
            echo "      <table class='table'>";
            echo "          <tr>";
            echo "              <td>";
            echo "                  59.1";
            echo "              </td>";
            echo "              <td>";
            echo "                  <b>Auto-indagação reflexiva:</b><br/>";
            echo "                  1. Qual é a desvantagem em dar esmola publicamente?<br/>";
            echo "                  2. Qual é a vantagem em dar esmola em secreto?<br/><br/>";
            echo "                  <b>Ao recolher-me, na hora da meditação, afinando a sintonia com o Mestre:</b><br>";
            echo "                  3. Qual é o valor da esmola (de dar e receber) para a meditação?";
            echo "              </td>";
            echo "          </tr>";
            echo "      </table>";
            echo "      </div>";
            echo "      <div class='text-center' style='color: red;'>Mateus 6:1-4</div>";
            echo "      <div align='justify' style='color: red;'>";
            echo "          1. Prestai atenção: não façais vossas boas obras diante dos homens, para serdes vistos por eles; senão não tereis recompensa junto de
vosso Pai que está nos céus.<br/>";
            echo "          2. Quando, pois, deres esmola, não faças tocar a trombeta diante de ti, como fazem os hipócritas nas sinagogas e nas ruas, para serem honrados pelos homens; em verdade vos digo: já receberam sua recompensa.<br/>";
            echo "          3. Tu, porém, quando deres esmola, não saiba tua mão esquerda o que faz tua direita.<br/>";
            echo "          4. para que tua esmola fique no secreto, e teu Pai, que vê no secreto, te retribuirá.<br/><br/>";
            echo "      </div>";
            echo "      <div class='text-center'>";
            echo "          <label style='color: blue;'>RedeUnaViva: Meditação Cristã<label style='color: red;'> 60 </label> – paragem <label style='color: red;'>124</label> – <label style='color: red;'>08.11.15</label></label>";
            echo "          <label style='color: red;'>MATEUS 6:5-15; MARCOS 11:25-26; LUCAS 11:1-4</label>";
            echo "      </div>";
            echo "  </div>";
            echo "</div>";
        echo "  </div>";
        echo "</div>";
        
        
        //Dinâmica da reunião
        echo "<div class='row' style='font-family: garamond; font-size: 20px; color: #1f226d;' align='justify'>";
        echo "  <div style='height: 20px;'>&nbsp;</div>";
//        echo "      <div class='col-xs-1 col-sm-1'>&nbsp;</div>";
        echo "      <div class='col-xs-12 col-sm-12'>";
        echo "          <p style='font-size: 20px; font-family: garamond; font-weight: bold; text-align: center;'>";
        echo "              DINÂMICA DA REUNIÃO DA MEDITAÇÃO CRISTÃ (MC)";
        echo "          </p>";
        echo "          <div style='height: 30px;'>&nbsp;</div>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify; ".$margem.";'>";
        echo "                  Este encontro compreende a reunião de pessoas afins e interessada em aprofundar o significado espiritual do Evangelho e tê-lo como ponto de partida para a vivência meditativa.";
        echo "          </p>";
        echo "          <br/>";
        echo "          <p style='text-align: justify; ".$tamanhoFonte16."; ".$margem.";'>";
        echo "              Há um focalizador que coordena a reunião e os convidados.";
        echo "          </p>";
        echo "          <br/>";
        echo "          <p style='text-align: justify; ".$tamanhoFonte16."; ".$margem.";'>";
        echo "              Como preliminar é oferecido um primeiro texto que contém os versículos do Evangelho que serão analisados e meditados naquele dia.";
        echo "          </p>";
        echo "          <br/>";
        echo "          <p style='text-align: justify; ".$tamanhoFonte16."; ".$margem.";'>";
        echo "              No convite, disposto nos dias que antecedem o domingo do encontro, no site da RUV, encontra-se este primeiro texto.";
        echo "          </p>";
        echo "          <br/>";
        echo "          <p style='text-align: justify; ".$tamanhoFonte16."; ".$margem.";'>";
        echo "              É solicitado aos participantes chegarem de 15 a 10 minutos antes do início da reunião para tomarem conhecimento do conteúdo que será abordado, quando é distribuído um segundo texto. Neste há o desenvolvimento do entendimento do conteúdo dos versículos.";
        echo "          </p>";
        echo "          <br/>";
        echo "          <p style='text-align: justify; ".$tamanhoFonte16."; ".$margem.";'>";
        echo "              A dinâmica da reunião parece com os encontros na sinagoga naquele tempo de Jesus, em que se lia um trecho da Torá e, a seguir, era facultada aos presentes, indistintamente, o uso da palavra, para que expressassem a sua compreensão.";
        echo "          </p>";
        echo "          <br/>";
        echo "          <p style='text-align: justify; ".$tamanhoFonte16."; ".$margem.";'>";
        echo "              Fazemos isto, no entendimento de que qualquer pessoa naquele momento pode veicular, como instrumento, a palavra inspirada e até iluminada, aquela que a maioria ou até mesmo uma única precisa ouvir. E também que a palavra verbalizada precisa ser ouvida, pelo menos por quem a diz.";
        echo "          </p>";
        echo "          <br/>";
        echo "          <p style='text-align: justify; ".$tamanhoFonte16."; ".$margem.";'>";
        echo "              A reunião da Meditação Cristã desenvolve-se dividida em 7 partes:<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              <b>1ª parte: Introdução e Leitura.</b><br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              1.	É procedida a leitura da Introdução que expõe, de forma resumida, do tema do estudo do dia.<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              2.	Nesta leitura estão incluídos os versículos escolhidos como fonte para a meditação.<br/><br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              <b>2ª parte: Primeira Meditação.</b><br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              3.	Há um tempo de 20 minutos de silêncio para uma primeira meditação, em busca da inspiração para a compreensão da palavra sagrada e, se possível, a fruição no seu sentido transcendente.<br/><br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              <b>3ª parte: O Comentário Principal.</b><br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              4.	O comentador principal é o focalizador da MC, ou um dos seus participantes assíduos, ou um visitante convidado que dispõe de 30 a 40 minutos para expor o que sua inspiração e estudo captaram sobre a passagem em evidência.<br/><br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              <b>6ª parte: Os Demais Comentários.</b><br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              5.	A palavra é franqueada a qualquer um dos participantes que tem a princípio até 10 minutos para compartilhar com o grupo o seu entendimento. Para isto ele apanha um bastão que fica numa tigela, no centro da sala. Enquanto ele estiver de posse do bastão, apenas ele tem o direito de falar. Se quiser, poderá também formular verbalmente uma pergunta. Ao terminar, ele devolve o bastão à tigela.<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              6.	Os próximos que tiverem o interesse em adicionar outro comentário procedem de forma similar ao do que lhe antecedeu.<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              7.	Se alguém quiser apenas fazer pergunta, esta ou estas deverão ser formuladas por escrito, sendo de responsabilidade do comentador principal responder.<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              8.	 Este deverá também apanhar o bastão e detê-lo enquanto responde. Quando terminar devolve o bastão à tigela.<br/>"; 
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              9.	Fica aberto ainda um tempo para quem quiser fazer outro comentário, inclusive responder à(s) pergunta(s) formulada(s).<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              10.	Esta parte tem a duração de 40 a 50 minutos.<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              11.	Qualquer comentador poderá falar mais de uma vez, desde que haja tempo hábil.<br/><br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              <b>7a parte: a segunda meditação.</b><br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              12.	A reunião termina com <b>uma meditação final que dura também 20 minutos</b>, como a inicial. Para esta, o focalizador escolhe um versículo do texto refletido como veículo para o estado meditativo.<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              13.	Na tigela em que fica o bastão são colocados os nomes escritos daquelas pessoas que os presentes desejam que possam ser beneficiadas com o mérito deste encontro. O focalizador conduz <b>a força mental do conjunto para este objetivo</b>, no final desta meditação.<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              14.	O tempo total da MC é de <b>2 horas</b>.<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify; ".$margem.";'>";
        echo "              Primamos pela fala reflexiva em vez do debate ou da polêmica.<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify; ".$margem.";'>";
        echo "              Evitamos que um fale para contestar o que o outro diz, como se houvesse uma fala mais certa. <br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              Valorizamos a fala de qualquer um porque esta tem um valor, mesmo que seja apenas para ele.<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify;'>";
        echo "              Se alguém não concordar, não precisa combater o primeiro. Basta, na sua hora, falar o seu pensamento sem, contudo, almejar concordância ou unanimidade.<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify; ".$margem.";'>";
        echo "              O uso do bastão é um procedimento valioso, porque produz naturalmente um lapso, mesmo que mínimo, entre uma fala e a seguinte.<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify; ".$margem.";'>";
        echo "              Com isto estamos a valorizar muito o silêncio. Às vezes, depois de uma fala, pode haver minutos de silêncio, até que alguém decida fazer uso da palavra de novo. O silêncio espontâneo tem o seu lugar e importância.<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify; ".$margem.";'>";
        echo "              O uso da escrita também contribui. Se uma pessoa não tem algo para falar mas apenas uma dúvida, o fato de ter que escrever a ajuda elaborar melhor o que deseja saber.<br/>";
        echo "          </p>";
        echo "          <p style='".$tamanhoFonte16."; text-align: justify; ".$margem.";'>";
        echo "              Tem sido uma experiência singular e enriquecedora esta meditação dominical em que sentimos a presença viva do Cristo,  como Mestre maior.";
        echo "          </p>";
//        echo "              </div>";
//        echo "          </p>";
        echo "      </div>";
//        echo "      <div class='col-xs-1 col-sm-1'>&nbsp;</div>";
        echo "</div>";//Fecha a div row
        
    }
    
    public function textoRetiro(){
        $tamanhoFonte16 = "font-size: 20px; font-family: garamond; text-align: justify;"; //; margin-left: 50px

        echo "<br/><br/>";
        echo "<div style='".$tamanhoFonte16."'>Conclui-se a Jornada Real de cada ano com um Retiro, que serve como avaliação deste percurso pelas 4 estações e preparação para o início de um novo tempo de vivências visando o autoconhecimento.</div><br/>";
        echo "<p style='".$tamanhoFonte16.";'>Funciona também como férias diferentes. Por que diferentes?</p><br/>";
        echo "<p style='".$tamanhoFonte16."'>Férias servem, a princípio, como descanso das atividades rotineiras. Muitas vezes são realizadas através de viagem por lugares desconhecidos, ou até mesmo através de revisitação de lugares já apreciados. De ordinário convidamos pessoas amigas e afins para tal jornada, mas em outras ocasiões até mesmo solitários nos aventuramos pelos caminhos. O lugar destas férias é conhecido, se já o frequentou antes, ou desconhecido, caso trate-se da sua primeira incursão por lá. Irá sozinho, mas acompanhado. Ou vice-versa.</p><br/>";
        echo "<p style='".$tamanhoFonte16.";'>Nosso itinerário mira o Espaço de Convivência Morgenlicht que pode ser conhecido virtualmente com o link do seu site abaixo.</p><br/>";
        
        echo "<p style='".$tamanhoFonte16.";'>O Morgen é um singular espaço de convivência, em beleza e conforto. Oferece um entorno favorável à introspecção e à harmonização dos nossos corpos e mente. A alimentação, cuidada com esmero, associa prazer com leveza, saúde com bem-estar.</p><br/>";
        
        echo "<p style='".$tamanhoFonte16.";'>Esta semana de retiro, em setembro, inicia-se sempre na manhã do sábado, quando procedemos a viagem de ida e termina após o almoço do sábado seguinte quando começa a viagem de retorno. A semana reservada é aquela que contém o feriado do dia 7 de setembro.</p><br/>";
        echo "<p style='".$tamanhoFonte16.";'>Neste tempo são propiciadas 7 jornadas diárias de uma jornada semanal, que constituem os principais ritmos de trabalho para o cultivo da vida interior. É favorecida uma vivência intensiva daquilo que é proposto como Jornada Real.</p><br/>";
        echo "<p style='".$tamanhoFonte16.";'>Os portais da manhã e da noite da jornada diária são momentos propícios de parada para transformar os conteúdos oníricos e as impressões dos acontecimentos diurnos, em encontro com a sabedoria perene.  Como preliminares facilitam a entrada em especiais estados de consciência, descobertos pela  prática da meditação.</p><br/>";
        echo "<p style='".$tamanhoFonte16.";'>Outro importante ciclo é o da jornada anual que, nesta perspectiva transpessoal, inicia-se em setembro, com a primavera, e através das 52 semanas seguintes compõe os 13  meses lunares, ou os 12 meses-RUV, uma efeméride para que individualmente e em grupo inventarie-se seu ano de labor, e haja nesta conclusão a compreensão adequada do investimento a ser realizado no próximo.</p><br/>";
        echo "<br/>";
        echo "<p style='".$tamanhoFonte16.";'><b>SERVIÇO:</b></p><br/>";
        echo "<p style='".$tamanhoFonte16.";'>Na proposta sem fins lucrativos, financeiramente falando, da Jornada Real, é cobrado um valor que pague os serviços do Morgenlicht e cubra as despesas com a organização do evento. No último ano (setembro-2015), este pacote ficou no valor de <b>R$ 1.400,00 (um mil e quatrocentos reais)</b>. Do ano 2016 ainda será fixado oportunarmente. O valor pode ser divido em 10 parcelas a serem pagas de março a dezembro, ou em 8, de abril a novembro, ou em 6 de abril a setembro.</p><br/>";
        echo "<p style='".$tamanhoFonte16.";'>";
        echo "<a href='http://www.morgenlicht.com.br/site07/portugues/inf.praticas/_private/inf.praticas.pdf' target='_blank'>http://www.morgenlicht.com.br/site07/portugues/inf.praticas/_private/inf.praticas.pdf</a><br/>";
        echo "<a href='http://www.morgenlicht.com.br/site07/portugues/sumario/index.htm' target='_blank'>http://www.morgenlicht.com.br/site07/portugues/sumario/index.htm</a>"; // style='margin-left: 50px;'
        echo "</p>";
        
        
    }
    
    public function textoJornadaMeditacao(){
    $fonteGaramond = "font-family: garamond";
    $tamanhoFonte = "font-size: 20px";
    $espacamento = "padding-left: 50px";
        echo "<div class='col-xs-12 col-sm-12 col-md-12'>";
        echo "  <div class='text-center' style='font-family: garamond; color: #1f226d;'>";
//        echo "  <div class='text-center' style='font-family: garamond; color: #3F6CA1;'>";
        echo "      <span style='color: #1f226d; font-size: 30px;'>";
        echo "          <b>Jornada de Meditação</b><br>";
        echo "      </span>";
        echo "      <span style='color: #1f226d; ".$tamanhoFonte.";'>";
        echo "          <b>Primavera e Outono</b><br><br>";
        echo "      </span>";
        echo "      <span style='".$tamanhoFonte.";'>";
        echo "          12 encontros para habilitar um modo especial <br>";
        echo "          de funcionamento da mente<br><br>";
        echo "          toque com delicadeza e agilidade o despertar da essência esquecida<br><br>";
        echo "          cultive sua fonte de bem estar <br>";
        echo "          e comprove a experiência da felicidade<br><br><br>";
        echo "      </span>";
        echo "  </div>";
        echo "</div>";
        echo "<div class='col-xs-12 col-sm-12 col-md-12' style='".$fonteGaramond."; color: #1f226d;'>";
        echo "  <div align='justify'>";
        echo "      <span style='font-size: 20px; '>";//antes, era 14, fora da fonte garamond ".$espacamento.";
        echo "          A meditação compõe com a Jornada Real o projeto de ação da RedeUnaViva. Favorece o desenvolvimento espiritual e habilita cada pessoa a disponibilizar sua oferta de benefícios, em prol de um mundo melhor. Contribui sutil e efetivamente para a instalação da já vislumbrada cultura de paz. Embutida na Jornada Real, ela se entrelaça com o processo de autoconhecimento, em prática estendida ao longo de um ano.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";//antes, era 14, fora da fonte garamond ".$espacamento.";
        echo "          Como Jornada de Meditação, disposta em uma estação, é oferecida em 12 encontros semanais. Ao proporcionar, por excelência, o encontro com o mestre interior, incrementa o labor da transformação de si mesmo, a caminho da factível auto-realização. Desta fusão, entre buscador e mestre, emergem sua riqueza em forma de sabedoria e de amor, potencialidade e dádiva de todo ser humano.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";//antes, era 14, fora da fonte garamond ".$espacamento.";
        echo "          Esta Jornada, disponibilizada duas vezes por ano, na primavera e no outono, apresenta sua filosofia e compartilha, em grupo afim, cinco preciosas conduções para este especial estado de consciência.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";//antes, era 14, fora da fonte garamond ".$espacamento.";
        echo "          Se você já apreendeu que sua natureza espiritual almeja vivências que ultrapassam o funcionamento ordinário da mente, se você já pressentiu que há um despertar interior à espera do seu investimento, é possível que tenhamos uma experiência singular a ser permutada nestes encontros.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";//antes, era 14, fora da fonte garamond ".$espacamento.";
        echo "          Para participar é preciso preencher a ficha de inscrição (<a href='formAdesao.php' target='_self'>clique aqui</a>).<br><br>";
        echo "      </span>";
        echo "<hr style='border-color: #1f226d;'>";
        echo "      <span style='font-size: 20px;'>";//antes, era 14, fora da fonte garamond ".$espacamento.";
        echo "          Informações:<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px;'>";//antes, era 14, fora da fonte garamond ".$espacamento.";
        echo "          Início da próxima Jornada de Meditação, em <b>19 de setembro de 2016</b>.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px;'>";//antes, era 14, fora da fonte garamond ".$espacamento.";
        echo "          Dia e horário: <b>2as feiras, de 19 às 20h30</b>.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px;'>";//antes, era 14, fora da fonte garamond ".$espacamento.";
        echo "          Endereço: <a href='contato.php#mapa' target='_self'>sede da RedeUnaViva</a> (ver à esquerda da barra horizontal, na base desta página ou no mapa, na aba “Contato”).<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px;'>";//antes, era 14, fora da fonte garamond  ".$espacamento.";
        echo "          Somos um grupo de voluntários que não recebe por qualquer serviço prestado. A cobrança visa unicamente a cobrir as despesas de aluguel da sala e gastos para o nosso desenvolvimento.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px;'>";//antes, era 14, fora da fonte garamond ".$espacamento.";
        echo "          Investimento: <b>R$ 120,00 </b>(por mês, a cada 4 semanas) ou <b>R$ 240,00</b>, a ser pago juntamente, com a sua inscrição.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px;'>";//antes, era 14, fora da fonte garamond ".$espacamento.";
        echo "          Contamos com sua compreensão e contribuição para o desenvolvimento desta Rede espiritual – a <b>RedeUnaViva</b>. Caso haja interesse em participar, mas dificuldade em arcar com o investimento financeiro, as portas estão abertas para encontrarmos a solução.";
        echo "      </span>";
        echo "  </div>";
        echo "</div>";
    }
    public function textoRodaDosSonhos(){
    $fonteGaramond = "font-family: garamond";
    $tamanhoFonte = "font-size: 20px";
    $espacamento = "padding-left: 50px";
        echo "<p style='height: 20px;'>&nbsp;</p>";
        echo "<div class='col-xs-12 col-sm-12 col-md-12'>";
        echo "  <div class='text-center' style='font-family: garamond; color: #1f226d;'>";
        echo "      <span style='".$tamanhoFonte.";'>";
        echo "          descubra como remover obstáculos ao crescimento pessoal <br>";
        echo "          através do poder instrínseco dos sonhos<br><br>";
        echo "          trabalhando os sonhos é possível conhecer padrões inconscientes<br>";
        echo "          que comprometem a saúde psíquica<br><br>";
        echo "          a partilha em grupo afim e cuidadoso enriquece os processos pessoais e coletivos<br><br><br>";
        echo "      </span>";
        echo "  </div>";
        echo "</div>";
        echo "<div class='col-xs-12 col-sm-12 col-md-12' style='".$fonteGaramond."; color: #1f226d;'>";
        echo "  <div align='justify'>";
        echo "      <span style='font-size: 20px; '>";
        echo "          Mensalmente, numa manhã de sábado, reúno-me com um grupo de pessoas interessadas em trabalhar psicologicamente seus sonhos, usando como referência principal uma teoria transpessoal autoral, desenvolvida nas últimas décadas.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          Os sonhos, ampliados através de vivências e análises, contribuem com o processo de autorrealização, incrementando novos elementos para o autoconhecimento.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          Segundo o sistema transpessoal, aos dois períodos naturais da jornada diária - o dia, com sua claridade, e a noite, com sua obscuridade, complementados para formar a unidade do ciclo diário - vinculam-se dois instigantes estados da consciência humana: a vigília, própria do <i>consciente solar</i>, e o onírico, afinado com o <i>inconsciente lunar</i>. Um também é claro, e o outro, sombrio. Um verbal, afirmativo e justificador, e o outro, imagético, alucinante e conspirador. Duas realidades do, subjetivismo que se colam, mais ou menos, com movimentos antagônicos e cooperativos, com a singela propriedade de promover a inteireza do ser humano, desde que criatiivamente integradas.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          Ao interessado em experimentar este processo, é facultado participar de uma Roda, mediante entrevista prévia. Tanto a entrevista como sua participação no grupo são oferecidas sem custo financeiro para o interessado. É um grupo aberto não apenas aos profissionais de saúde, mas para todo aquele que se interessa no mergulho interior.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "         Contato por e-mail ou por telefone.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          Focalizador: <b>Luiz Carlos Bernal - Médico e Psicoterapeuta</b>. Mestre pelo HCTE-UFRJ, com o tema vinculado aos estudos da Consciência.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          <b>Informações:</b><br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          Próxima Roda: ver calendário abaixo.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          Horário: <b>de 9h às 13h</b><br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";//antes, era 14, fora da fonte garamond ".$espacamento.";
        echo "          Endereço: <a href='contato.php#mapa' target='_self'>sede da RedeUnaViva</a>.<br><br>";
        echo "      </span>";
        echo "  </div>";
        echo "</div>";
    }
    public function textoRedeSocialClinica(){
    $fonteGaramond = "font-family: garamond";
    $tamanhoFonte = "font-size: 20px";
    $espacamento = "padding-left: 50px";
        echo "<p style='height: 30px;'>&nbsp;</p>";
        echo "<div class='col-xs-12 col-sm-12 col-md-12' style='".$fonteGaramond."; color: #1f226d;'>";
        echo "  <div align='justify'>";
        echo "      <span style='font-size: 20px; '>";
        echo "          Compartilhando o entendimento de que a psicoterapia é promotora da saúde física, emocional e psíquica, a RUV oferece o serviço de atendimento psicoterapêutico através da Rede Social Clínica. O serviço se destina àqueles cuja condição financeira não se adequa aos valores praticados usualmente no mercado. A Rede Social Clínica é formada por psicólogos e terapeutas - membros da RUV - que dispõem de horários específicos para esse atendimento. Na entrevista inicial é acordado o valor do serviço, assim como também são transmitidas as regras do contrato.";
        echo "      </span>";
        echo "  </div>";
        
        echo "  <div style='height: 20px;'>&nbsp;</div>";
        echo "  <div class='alert alert-info' role='alert'>";
        echo "      <div class='text-center' style='font-family: garamond; font-size: 20px;'>";
        echo "          Contato para marcar entrevista ou para outras informações no telefone (21) 2266-5690";
        echo "      </div>";
        echo "  </div>";
        
        echo "</div>";
    }
    public function textoTranscursoTranspessoal(){
    $fonteGaramond = "font-family: garamond";
    $tamanhoFonte = "font-size: 20px";
    $espacamento = "padding-left: 50px";
        echo "<p style='height: 20px;'>&nbsp;</p>";
        echo "<div class='col-xs-12 col-sm-12 col-md-12'>";
        echo "  <div class='text-center' style='font-family: garamond; color: #1f226d;'>";
        echo "      <span style='".$tamanhoFonte.";'>";
        echo "          apresenta uma teoria autoral que justifica a estruturação e desenvolvimento da<br>";
        echo "          personalidade em consonância com a realidade espiritual<br><br>";
        echo "          mostra a coincidência da saúde mental com a felicidade<br>";
        echo "          apontando caminhos para a autorrealização<br><br>";
        echo "      </span>";
        echo "  </div>";
        echo "</div>";
        echo "<div class='col-xs-12 col-sm-12 col-md-12' style='".$fonteGaramond."; color: #1f226d;'>";
        echo "  <div align='justify'>";
        echo "      <span style='font-size: 20px; '>";
        echo "          Ao longo das últimas décadas venho desenvolvendo uma teoria psicológica decorrente de particular leitura do Sistema Transpessoal, aplicada com mais especificidade no campo da psicoterapia e do desenvolvimento pessoal.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          O empenho desta teoria, em afinidade com a proposta transpessoal, visa a integração entre a psicologia ociedental, mais formal, e a abordagem espiritual desenvolvida pelas Tradições da Sabedoria Antiga. Além de beber nas fontes da psicanálise e da psicologia analítica, que centram seu trabalho terapêutico no modelo clássico da relação terapeuta-paciente, busquei sua complementação no investimento psicológico da introspecção, sustentados por estes sistemas espirituais, ao longo de milênios. Eles promovem o autoconhecimento para além das fronteiras do ego, a partir da especialíssima e diferente relação a dois - a do mestre com o discípulo.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          Os quatro pilares em que se assenta o Transcuro transpessoal são:<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; margin-left: 25px;'>";
        echo "          Psicodinâmica do ego<br/>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; margin-left: 25px;'>";
        echo "          Cosmogênese do ego<br/>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; margin-left: 25px;'>";
        echo "          Ontogênese do ego<br/>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; margin-left: 25px;'>";
        echo "          Roda das estações da vida";
        echo "      </span>";
        echo "          <br><br>";
        echo "      <span style='font-size: 20px; '>";
        echo "          O Transcurso acontece uma vez por mês, às 6ªs. feiras, no horário de 14h às 18h.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          A medicação, por pressuposto, permeia tanto o campo de estudo como o da prática terapêutica.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          Investigar e testar a teoria com a clínica fez gerar uma forma diferenciada de supervisão em grupo, a Transvisão. Sua frequência é também mensal, às 6ªs feiras, de 14h às 16:30h.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          O ingresso no Transcurso é realizado mediante entrevista prévia e está aberto a todo aquele interessado no tema. A Transvisão é acessível apenas aos profissionais que trabalham em campo afim. Contato por e-mail ou por telefone.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          <b>Informações:</b><br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          Focalizador: <b>Luiz Carlos Bernal</b> - Médico e Psicoterapeuta. Mestre pelo HCTE-UFRJ, com o tema vinculado aos estudos da Consciência.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          Próximo encontro: ver calendário.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          Horário: <b>de 13h às 18h</b>.<br><br>";
        echo "      </span>";
        echo "      <span style='font-size: 20px; '>";
        echo "          Endereço: <a href='contato.php#mapa' target='_self'>sede da RedeUnaViva</a>.<br><br>";
        echo "      </span>";
        echo "  </div>";
        echo "</div>";
    }
    
}
